ZeusWPI/Haldis

- README.md
> Rename to James

- app/templates/home.html
Some major changes to the project. Please review.
> punctuation is overrated

- app/utils.py
> improved formatting of prices

- app/templates/order.html
- app/templates/utils.html
Show closing time AND countdown on home and order page, added startdate and starttime on order page.
Format: starttime: dd/mm/yy hh:mm, closing time: hh:mm, countdown:  hh:mm:ss
> Date time update

- app/static/js/map.js
> fixed poput location

- app/static/js/map.js
- app/templates/maps.html
> added open new tab on marker click

- app/templates/order_edit.html
> fixed Create new order message on order edit

- app/templates/location.html
- app/templates/locations.html
- app/views/order.py
> Adds a button on the location/ and locations/ page to start a new order

- README.md
- app/static/css/main.css
- app/static/css/map.css
- app/static/js/map.js
- app/templates/location.html
- app/templates/maps.html
> #104 adds a map to the locations

- app/database/create_database.py
If people fuck it up it would be on their local system, only the sysadmin can fuck up the real haldis
> Remove the long extra confirmation

- app/static/css/main.css
- app/static/js/darkmode.js
- app/templates/layout.html
- app/templates/order_edit.html
> Added dark mode

- app/static/css/main.css
- app/static/js/darkmode.js
- app/templates/layout.html
The user can toggle between dark and light mode without restrictions.
The text on the blue buttons stays white to improve the user interaction.
> Dark theme users can toggle off darkmode + button color fix

- app/static/css/main.css
Color en UI fixes + logica in de volgorde van het css bestand verbeterd.
> color and ui fixes

- app/static/css/main.css
Dark theme does not interfere with the light theme. Dark theme works for input fields and date picker.
> Added Dark mode for input fields + Dark mode does not interfere with Light mode.

- app/templates/order.html
- app/templates/order_items.html
> Make it easier to distinguish orders from

- app/static/js/customThemes.js
- app/templates/layout.html
- app/templates/profile.html
- app/views/general.py
Added dropdown to select custom themes (in profile page)
> Fix multiple css

- .pylintrc
- app/add_admins.py
- app/admin.py
- app/app.py
- app/create_database.py
- app/fatmodels.py
- app/forms.py
- app/hlds/__init__.py
- app/hlds/definitions.py
- app/hlds/models.py
- app/hlds/parser.py
- app/login.py
- app/migrations/env.py
- app/migrations/versions/9159a6fed021_initial_haldis_support.py
- app/models/order.py
- app/models/orderitem.py
- app/models/orderitemchoice.py
- app/models/user.py
- app/notification.py
- app/parse_hlds.py
- app/utils.py
- app/views/debug.py
- app/views/general.py
- app/views/order.py
- app/views/stats.py
- app/zeus.py
- pylint-requirement.txt
Fix a big part of all pylint errors in preparation for the CI pylint checker
> Fix pylint in haldis

- .pylintrc
- app/admin.py
- app/app.py
- app/create_database.py
- app/fatmodels.py
- app/forms.py
- app/parse_hlds.py
- app/utils.py
Except hlds related files because that's a mess
> Fix pylint on everything

- populate-db.sh
This fixes the problem where generating a migration does literally nothing.
> Make sure to stamp database at latest revision after setup

- app/models/order.py
Jasper in Mattermost
> de slugs in haldis zijn niet case sensitive
base58 is mss een goed idee?
want nu zijn 0'en en O's verwarbaar
> Use base58 for slugs

- app/migrations/versions/29ccbe077c57_add_slug.py
- app/models/order.py
@redfast00 said editing the old migration was fine.
> Make slug eight characters

- app/templates/order.html
Forms in forms are not allowed.
> Fix not being able to delete an item from the list at the bottom of an order

- app/forms.py
> Order current user to the top for admins when choosing courier

- app/hlds/hlds.tatsu
> Remove double space requirement

- app/static/css/themes/christmas_heavy.css
> change gray2 in christmas theme to be more readable

- app/templates/order.html
- app/views/order.py
> add a button to extend the order by 3 minutes

- app/hlds/models.py
- app/hlds/parser.py
This would have caught the error we had during our foleys deployment minutes before our order.
> Add hlds validation check that choice options are correctly set

- app/forms.py
> Pass through arguments to validate, fixes #232
